services:
  messages-api:
    image: harishankarn/payment-messages-api
    build: .
    container_name: messages-api
    ports:
      - "8080:8080" # Expose port 8080 from the container to the host
    restart: always  # Automatically restart the container if it crashes
